baseURL: "https://FabriDeCastelli.github.io/"
title: Fabrizio De Castelli
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
ShowAllPagesInArchive: true

pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Projects
      url: projects/
      weight: 3
    - name: Interests
      url: interests/
      weight: 4
    - name: About
      url: about/
      weight: 5  
    - name: Contact
      url: contact/
      weight: 6
    - name: CV
      url: cv.pdf
      weight: 7
    

params:
  author: Fabrizio De Castelli
  description: "This website hosts Fabrizio De Castelli's personal information."

  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  MainSections: ["projects"]

  # Appearance and functionality
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true

  comments: false
  math: true


  profileMode:
    enabled: true
    title: Fabrizio De Castelli
    subtitle: >
      I am a MSc student in Computer Science at the Computer Science Department, University of Pisa.
    imageUrl: "profile.jpeg"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: CV
        url: cv.pdf
      - name: About
        url: about/
      - name: Interests
        url: interests/
      - name: Projects
        url: projects/
      - name: Contact
        url: contact/

  socialIcons:
    - name: Email
      url: mailto:decastellifabrizio@gmail.com
    - name: GitHub
      url: https://github.com/FabriDeCastelli
    - name: CV
      url: cv.pdf

  label:
    text: "Fabrizio De Castelli"
    icon: favicon.ico
    iconHeight: 18

  assets:
    disableScrollBarStyle: true

  cover:
    hiddenInList: false
    hiddenInSingle: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
